setup:
  nb_timesteps: &nb_timesteps 500000
  checkpoint_freq: 50
  checkpoint_at_end: True
  keep_checkpoints_num: 5
  checkpoint_score_attr: evaluation/episode_reward_mean
  verbose: 1
  # storage_path: /home3/s3374610/mahrl_grid2op/runs/ # 
  storage_path: /Users/barberademol/Documents/GitHub/mahrl_grid2op/runs/ #/home3/s3374610/mahrl_grid2op/runs/ 
  experiment_name: l2rpn_case14_sandbox/opponent_single_network
  save_artifact: True
  num_samples: 2

debugging:
  seed: &seed !randint [0, 100000]

training:
  # tunable parameters
  # gamma: 0.99 # !grid_search [0.95, 0.99]
  lr: !grid_search [5e-3, 5e-4, 5e-5] #0.0001 # !grid_search [0.00005, 0.0005, 0.005]
  # vf_loss_coeff: 0.5
  # kl_coeff: 0.2
  # entropy_coeff: 0.01
  # clip_param: 0.3
  # lambda_: 0.95
  num_sgd_iter: !grid_search [5, 15] #15
  sgd_minibatch_size: !grid_search [64, 256, 518] #256 # !grid_search [32, 64, 128]
  train_batch_size: !grid_search [1024, 2048, 4048] #1024
  model:
    fcnet_hiddens: 
    - 256
    - 256
    - 256
    fcnet_activation: relu
  _enable_learner_api: False
  batch_mode: complete_episodes

rl_module:
  _enable_rl_module_api: False

explore:
  exploration_config:
    type: StochasticSampling

callbacks:
  callbacks: !CustomMetricsCallback

framework:
  framework: torch

multi_agent:
  policy_mapping_fn: !policy_mapping_fn
  policies_to_train: ["reinforcement_learning_policy"]
  count_steps_by: agent_steps

environment:
  env_config: &env_config_train
    env_name: l2rpn_case14_sandbox_train
    num_agents: 3
    action_space: medha_reversed
    # lib_dir: /home3/s3374610/mahrl_grid2op/ 
    lib_dir: /Users/barberademol/Documents/GitHub/mahrl_grid2op/ # /home3/s3374610/mahrl_grid2op/ 
    max_tsteps: *nb_timesteps
    grid2op_kwargs:
      # general kwargs
      reward_class: !ScaledL2RPNReward
      # kwargs specific to opponents
      opponent_attack_cooldown: 144 # max 2 attacks per day
      opponent_attack_duration: 48 # 4 hours in a day
      opponent_budget_per_ts: 0.333343333333 # taken from blazej, (opponent_attack_duration / opponent_attack_cooldown) + 1e-5
      opponent_init_budget: 144
      opponent_action_class: !PowerlineSetAction 
      opponent_class: !RandomLineOpponent
      opponent_budget_class: !BaseActionBudget
      opponent_space_type: !ReconnectingOpponentSpace
      kwargs_opponent:
        lines_attacked: 
          - '3_4_6'
          - '11_12_13'
          - '3_6_15'
          - '3_8_16'
          - '6_8_19'
    seed: *seed
    rho_threshold: 0.95
    shuffle_scenarios: True

env_config_val: &env_config_val
  <<: *env_config_train
  env_name: l2rpn_case14_sandbox_val
  shuffle_scenarios: False

evaluation:
  evaluation_interval: 2
  evaluation_duration: 100 # as many as there are validation episodes
  evaluation_duration_unit: episodes
  evaluation_config: 
    env_config: *env_config_val # use the validation environment
    explore: True

resources:
  num_gpus: 0
  num_learner_workers: 6

rollouts:
  num_rollout_workers: 4