setup:
  nb_timesteps: &nb_timesteps 100000
  # checkpoint_freq: 100000
  verbose: 1
  storage_path: /Users/barberademol/Documents/GitHub/mahrl_grid2op/runs/ # /home3/s3374610/mahrl_grid2op/runs/ # 
  experiment_name: rte_case14_example/ppo_baseline/initial_gridsearch
  save_artifact: True
  num_samples: 2

debugging:
  seed: &seed 20

training:
  # tunable parameters
  gamma: 0.99 # !grid_search [0.95, 0.99]
  lr: !grid_search [0.05, 0.005, 0.0005]
  vf_loss_coeff: 0.5
  entropy_coeff: 0.01
  clip_param: 0.2
  lambda_: 0.95
  num_sgd_iter: !grid_search [5, 15]
  sgd_minibatch_size: 256 # !grid_search [32, 64, 128]
  train_batch_size: 1024
  batch_mode: complete_episodes
  model:
    fcnet_hiddens: 
    - 256
    - 256
    - 256
  _enable_learner_api: False
  
rl_module:
  _enable_rl_module_api: False

explore:
  exploration_config:
    type: StochasticSampling

callbacks:
  callbacks: !CustomMetricsCallback

framework:
  framework: torch

multi_agent:
  policy_mapping_fn: !policy_mapping_fn
  policies_to_train: ["reinforcement_learning_policy"]

environment:
  env_config: &env_config_train
    env_name: rte_case14_realistic_train
    num_agents: 3
    action_space: tennet
    lib_dir: /Users/barberademol/Documents/GitHub/mahrl_grid2op/ #  /home3/s3374610/mahrl_grid2op/ 
    max_tsteps: *nb_timesteps
    grid2op_kwargs:
      # general kwargs
      reward_class: !LossReward
    seed: *seed
    rho_threshold: 0.95

env_config_val: &env_config_val
  <<: *env_config_train
  env_name: rte_case14_realistic_val

evaluation:
  evaluation_interval: 5
  evaluation_duration: 100 # as many as there are validation episodes
  evaluation_duration_unit: episodes
  evaluation_config: 
    explore: False
    env_config: *env_config_val # use the validation environment

resources:
  num_cpus: 6

rollouts:
  rollout_fragment_length: 128