setup:
  max_ep_len: 2016
  nb_timesteps: 10_000
  checkpoint_freq: 2 # number of iterations between checkpoints (1 iteration = 1 agent update?)
  checkpoint_trainable_policies_only: True
  verbose: 1
  storage_path: ./runs #/Users/barberademol/Documents/GitHub/mahrl_grid2op/runs/ #/home3/s3374610/mahrl_grid2op/runs/

debugging:
  seed: &seed 14

training:
  # tunable parameters
  lr: 0.003 # !grid_search [0.0005, 0.005, 0.05]
  gamma: 0.95 # !grid_search [0.95, 0.99]
  vf_loss_coeff: 0.5
  entropy_coeff: 0.01
  clip_param: 0.2
  lambda_: 0.95
  num_sgd_iter: 4
  sgd_minibatch_size: 32
  train_batch_size: &train_batch_size 128 # !grid_search [32, 64, 128]
  batch_mode: complete_episodes
  model:
    fcnet_hiddens:
    - 128
    - 128
    - 128
#    fcnet_activation: relu
  _enable_learner_api: False

rl_module:
  _enable_rl_module_api: False

explore:
  exploration_config:
    type: StochasticSampling

callbacks:
  callbacks: !CustomMetricsCallback

framework:
  framework: torch

multi_agent:
  policy_mapping_fn: !policy_mapping_fn
  policies_to_train: ["reinforcement_learning_policy"]
  count_steps_by: agent_steps

environment:
  env_config: &env_config_train
    env_name: rte_case5_example
    action_space: asymmetry
    lib_dir: /Users/ericavandersar/Documents/Python_Projects/Research/mahrl_grid2op/ #/Users/barberademol/Documents/GitHub/mahrl_grid2op/ # /home3/s3374610/mahrl_grid2op/
    max_tsteps: *train_batch_size
    grid2op_kwargs:
      # general kwargs
      test: True
      reward_class: !LossReward
    seed: *seed
    rho_threshold: 0.90

env_config_val: &env_config_val
  <<: *env_config_train
  env_name: rte_case5_example_per_day_val

evaluation:
  evaluation_interval: 10
  evaluation_duration: 14 # as many as there are validation episodes
  evaluation_duration_unit: episodes
  evaluation_config:
    env_config: *env_config_val # use the validation environment

#scaling_config:
#  num_workers: 4

resources:
  num_learner_workers: 1

rollouts:
  num_rollout_workers: 1
