setup:
  nb_timesteps: &nb_timesteps 600000
  checkpoint_freq: 0
  checkpoint_at_end: False
  # keep_checkpoints_num: 0
  checkpoint_score_attr: evaluation/episode_reward_mean
  verbose: 1
  storage_path: /Users/barberademol/Documents/GitHub/mahrl_grid2op/runs/ # /home3/s3374610/mahrl_grid2op/runs/ # 
  experiment_name: l2rpn_case14_sandbox/RLv_RLv
  save_artifact: True
  num_samples: 1

debugging:
  seed: &seed !randint [0, 100000]

training:
  # tunable parameters
  lr: !grid_search [5e-3, 5e-4, 5e-5] # !grid_search [0.00005, 0.0005, 0.005]
  num_sgd_iter: !grid_search [5, 15]
  sgd_minibatch_size: !grid_search [126, 256, 518] # !grid_search [32, 64, 128]
  train_batch_size: !grid_search [1024, 2048, 4048]
  # lr: 0.0001 # !grid_search [0.00005, 0.0005, 0.005]
  # num_sgd_iter: 5
  # sgd_minibatch_size: 256 # !grid_search [32, 64, 128]
  # train_batch_size: 1024
  model:
    fcnet_hiddens: 
    - 256
    - 256
    - 256
    fcnet_activation: relu
  _enable_learner_api: False
  batch_mode: complete_episodes

rl_module:
  _enable_rl_module_api: False

explore:
  exploration_config:
    type: StochasticSampling

callbacks:
  callbacks: !CustomMetricsCallback

framework:
  framework: torch

multi_agent:
  policy_mapping_fn: !policy_mapping_fn
  policies_to_train: ["reinforcement_learning_policy"]
  count_steps_by: agent_steps

environment:
  env_config: &env_config_train
    env_name: l2rpn_case14_sandbox_train
    num_agents: 3
    action_space: tennet
    lib_dir: /Users/barberademol/Documents/GitHub/mahrl_grid2op/ #  /home3/s3374610/mahrl_grid2op/ # 
    max_tsteps: *nb_timesteps
    grid2op_kwargs:
      # general kwargs
      reward_class: !ScaledL2RPNReward
    rho_threshold: 0.95
    shuffle_scenarios: True
    stage: train
    prio: True

env_config_val: &env_config_val
  <<: *env_config_train
  env_name: l2rpn_case14_sandbox_val
  shuffle_scenarios: False
  stage: val

evaluation:
  evaluation_interval: 20
  evaluation_duration: 100 # as many as there are validation episodes
  evaluation_duration_unit: episodes
  num_evaluation_workers: 1
  evaluation_config: 
    env_config: *env_config_val # use the validation environment
    explore: True

resources:
  num_gpus: 0
  num_learner_workers: 1

rollouts:
  num_rollout_workers: 1